### ISSUE TITLE
InventoryD is check only jump

### ISSUE THREAD

**Issue by Dg32z** [Axionize/LightningGrim#22] opened 2024-12-14 16:20 UTC
### Describe the bug and how to replicate it

  VectorData.MoveVectorData move = findMovement(player.predictedVelocity); 
 'move' should always be null, so its detection of player movement will not work
![1](https://github.com/user-attachments/assets/9152ddb3-95d8-4319-bdf4-f333ee8af19a)
![2](https://github.com/user-attachments/assets/3f48c4ec-bc89-4ec9-ac42-1adfa63c25e2)

### Grim version

Not important

### Server version

Not important

### Plugins

Not important

**Comment by Axionize** [comment] 2024-12-14 22:35
> ### Describe the bug and how to replicate it
> VectorData.MoveVectorData move = findMovement(player.predictedVelocity); 'move' should always be null, so its detection of player movement will not work ![1](https://private-user-images.githubusercontent.com/100349169/395797011-9152ddb3-95d8-4319-bdf4-f333ee8af19a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMTUyOTIsIm5iZiI6MTczNDIxNDk5MiwicGF0aCI6Ii8xMDAzNDkxNjkvMzk1Nzk3MDExLTkxNTJkZGIzLTk1ZDgtNDMxOS1iZGY0LWYzMzNlZThhZjE5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQyMjIzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTBjZDA4M2Y0Mzg2MTcyNWQ0MDVhN2JmYTViMWU5OGY3OWIyZjM1OTAyY2IzNTEzOGM4YjI3MzI4NTE3ZGQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gvIY8HzLEBAS2AIA9sKsc3woCk6HCteOfPUbQFIoK6Q) ![2](https://private-user-images.githubusercontent.com/100349169/395797017-3f48c4ec-bc89-4ec9-ac42-1adfa63c25e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMTUyOTIsIm5iZiI6MTczNDIxNDk5MiwicGF0aCI6Ii8xMDAzNDkxNjkvMzk1Nzk3MDE3LTNmNDhjNGVjLWJjODktNGVjOS1hYzQyLTFhZGZhNjNjMjVlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQyMjIzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmFlZjk4ZTNiMWQ1YTBkNTRlNzk4NDk3NDY4ZWJkYTc0MTFkN2NlYmIwNGZlNTBlMWJkODJlY2MxOTJlNzdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dSY90EJ_eV_9O3QF3aZTxuPpKchwVScYk78CnCEO-Bk)

I have no idea what this supposed is supposed to be. What you're saying doesn't make sense, why would you want it be `null` all the time? The code in your picture is barely related to the code you're describing!

As far as I'm aware we can't detect when the player opens an inventory client side and is moving. We can detect when they open the inventory and try to move the item though while moving which InventoryD checks for. This check works as intended, so I'm not sure what you're trying to say here.

If you mean to imply there is a bug with InventoryD please demonstrate it. If you mean to imply that we can improve InventoryD to detect when a player is walking with their inventory open, please say so explicitly (or if you know the code of the problem so well and how to fix it, make a PR to fix it). I can't help you if you don't bother to explain what the actual issue at hand is.

**Comment by Dg32z** [comment] 2024-12-15 03:25
> > ### Describe the bug and how to replicate it
> > VectorData.MoveVectorData move = findMovement(player.predictedVelocity); 'move' should always be null, so its detection of player movement will not work ![1](https://private-user-images.githubusercontent.com/100349169/395797011-9152ddb3-95d8-4319-bdf4-f333ee8af19a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMTUyOTIsIm5iZiI6MTczNDIxNDk5MiwicGF0aCI6Ii8xMDAzNDkxNjkvMzk1Nzk3MDExLTkxNTJkZGIzLTk1ZDgtNDMxOS1iZGY0LWYzMzNlZThhZjE5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQyMjIzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTBjZDA4M2Y0Mzg2MTcyNWQ0MDVhN2JmYTViMWU5OGY3OWIyZjM1OTAyY2IzNTEzOGM4YjI3MzI4NTE3ZGQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gvIY8HzLEBAS2AIA9sKsc3woCk6HCteOfPUbQFIoK6Q) ![2](https://private-user-images.githubusercontent.com/100349169/395797017-3f48c4ec-bc89-4ec9-ac42-1adfa63c25e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMTUyOTIsIm5iZiI6MTczNDIxNDk5MiwicGF0aCI6Ii8xMDAzNDkxNjkvMzk1Nzk3MDE3LTNmNDhjNGVjLWJjODktNGVjOS1hYzQyLTFhZGZhNjNjMjVlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQyMjIzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmFlZjk4ZTNiMWQ1YTBkNTRlNzk4NDk3NDY4ZWJkYTc0MTFkN2NlYmIwNGZlNTBlMWJkODJlY2MxOTJlNzdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dSY90EJ_eV_9O3QF3aZTxuPpKchwVScYk78CnCEO-Bk)
> 
> I have no idea what this supposed is supposed to be. What you're saying doesn't make sense, why would you want it be `null` all the time? The code in your picture is barely related to the code you're describing!
> 
> As far as I'm aware we can't detect when the player opens an inventory client side and is moving. We can detect when they open the inventory and try to move the item though while moving which InventoryD checks for. This check works as intended, so I'm not sure what you're trying to say here.
> 
> If you mean to imply there is a bug with InventoryD please demonstrate it. If you mean to imply that we can improve InventoryD to detect when a player is walking with their inventory open, please say so explicitly (or if you know the code of the problem so well and how to fix it, make a PR to fix it). I can't help you if you don't bother to explain what the actual issue at hand is.

MoveVectorData has never been assigned a value, so it cannot work when you want to call its' x, z '

**Comment by Dg32z** [comment] 2024-12-15 03:25
> > ### Describe the bug and how to replicate it
> > VectorData.MoveVectorData move = findMovement(player.predictedVelocity); 'move' should always be null, so its detection of player movement will not work ![1](https://private-user-images.githubusercontent.com/100349169/395797011-9152ddb3-95d8-4319-bdf4-f333ee8af19a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMTUyOTIsIm5iZiI6MTczNDIxNDk5MiwicGF0aCI6Ii8xMDAzNDkxNjkvMzk1Nzk3MDExLTkxNTJkZGIzLTk1ZDgtNDMxOS1iZGY0LWYzMzNlZThhZjE5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQyMjIzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTBjZDA4M2Y0Mzg2MTcyNWQ0MDVhN2JmYTViMWU5OGY3OWIyZjM1OTAyY2IzNTEzOGM4YjI3MzI4NTE3ZGQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gvIY8HzLEBAS2AIA9sKsc3woCk6HCteOfPUbQFIoK6Q) ![2](https://private-user-images.githubusercontent.com/100349169/395797017-3f48c4ec-bc89-4ec9-ac42-1adfa63c25e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMTUyOTIsIm5iZiI6MTczNDIxNDk5MiwicGF0aCI6Ii8xMDAzNDkxNjkvMzk1Nzk3MDE3LTNmNDhjNGVjLWJjODktNGVjOS1hYzQyLTFhZGZhNjNjMjVlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQyMjIzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmFlZjk4ZTNiMWQ1YTBkNTRlNzk4NDk3NDY4ZWJkYTc0MTFkN2NlYmIwNGZlNTBlMWJkODJlY2MxOTJlNzdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dSY90EJ_eV_9O3QF3aZTxuPpKchwVScYk78CnCEO-Bk)
> 
> I have no idea what this supposed is supposed to be. What you're saying doesn't make sense, why would you want it be `null` all the time? The code in your picture is barely related to the code you're describing!
> 
> As far as I'm aware we can't detect when the player opens an inventory client side and is moving. We can detect when they open the inventory and try to move the item though while moving which InventoryD checks for. This check works as intended, so I'm not sure what you're trying to say here.
> 
> If you mean to imply there is a bug with InventoryD please demonstrate it. If you mean to imply that we can improve InventoryD to detect when a player is walking with their inventory open, please say so explicitly (or if you know the code of the problem so well and how to fix it, make a PR to fix it). I can't help you if you don't bother to explain what the actual issue at hand is.

Wait for me to upload the video, this will make you understand

**Comment by Dg32z** [comment] 2024-12-15 03:27
https://github.com/user-attachments/assets/86900768-9226-44c9-8430-976450984d73

**Comment by Dg32z** [comment] 2024-12-15 03:28
Or please try System.out.println(move);

**Comment by Axionize** [comment] 2024-12-15 20:02
Ah I understand now. This should be fixed in B37. Please tell me if you have any more related issues in this thread!

**Closed as completed** 2024-12-15 22:14 UTC
Labels: bug
