### ISSUE TITLE
LOSP False Positive

### ISSUE THREAD

**Issue by overkidding** [Axionize/LightningGrim#3] opened 2024-10-29 09:39 UTC
### Describe the false positive and how to replicate it

1. Stand on top of a low grass like in the attachment, place one also 2 blocks away, try to place a Bed block, this will false pre-flying
![image](https://github.com/user-attachments/assets/0b5cba19-efec-47f5-98ed-b714113f7d19)

### Grim version

Latest

### Server version

1.8.8

### Client version

1.8.9

### Plugins

ProtocolLib, ViaVersion, Grim

**Comment by Axionize** [comment] 2024-11-03 12:49
I'll look into it

**Comment by Axionize** [comment] 2024-11-03 23:48
This is caused by a bug in packetevents. I've made a PR for the fix soon but we have to wait for it to reach the next release.
https://github.com/retrooper/packetevents/pull/1053

**Comment by Axionize** [comment] 2024-11-15 01:04
https://modrinth.com/plugin/lightning-grim-anticheat

Download grimac-2.3.69-custom-packetevents-2.6.1-fix-mappings (2.3.69-custom-a1) off of modrinth. Should be fixed. Tell me if that jar still has issues.

**Comment by Axionize** [comment] 2024-11-15 03:34
Note that there remains a similar issue that has to deal with item mappings in packetevents (from placing the literal short_grass item as blocks on 1.8) that has yet to be fixed. You will not run in this unless you're giving your players short grass to place though.

EDIT I fixed all of this in B9 download that version or newer from modrinth.
https://modrinth.com/plugin/lightning-grim-anticheat

Please re-open this issue if the new version does not fix it.

**Closed as completed** 2024-11-15 05:45 UTC
Labels: dependency bug, fixed
