### ISSUE TITLE
False positive in BlockRayTrace

### ISSUE THREAD

**Issue by AbdisKiosk** [Axionize/LightningGrim#5] opened 2024-11-09 00:49 UTC
### Describe the false positive and how to replicate it

Not sure if this is the same issue as https://github.com/Axionize/LightningGrim/issues/3

You need two players, place them like the image
![Image 1](https://github.com/user-attachments/assets/c533723a-48ce-4ba6-846c-4a5ffc09b6a9)
Then, you should try to hit through the grass:
![Image 2](https://github.com/user-attachments/assets/53373bad-92e1-464f-a437-9b9d285234ff)

Video example: https://github.com/user-attachments/assets/cf2e2609-7c18-4345-bfd5-f03a702c4b47

### Grim version

Latest

### Server version

PandaSpigot

### Client version

Video is with Labymod, I also tested with vanilla

### Plugins

TAB, PacketEvents, ViaVersion, Grim, WorldEdit, WorldGuard

**Comment by overkidding** [comment] 2024-11-09 16:36
Same as https://github.com/Axionize/LightningGrim/issues/3 just wait

**Comment by AbdisKiosk** [comment] 2024-11-09 19:54
Just tried compiling with his the changes from the pr, it still falses

**Comment by overkidding** [comment] 2024-11-09 20:46
> Just tried compiling with his the changes from the pr, it still falses

You meant by compiling the changes of packet events?

**Comment by AbdisKiosk** [comment] 2024-11-09 21:10
> > Just tried compiling with his the changes from the pr, it still falses
> 
> You meant by compiling the changes of packet events?

Yes

**Comment by overkidding** [comment] 2024-11-11 18:37
@Axionize than i think its not the packetevents thing that is broken also in mine

> > > Just tried compiling with his the changes from the pr, it still falses
> > 
> > 
> > You meant by compiling the changes of packet events?
> 
> Yes

**Comment by Axionize** [comment] 2024-11-12 01:40
That's interesting should be fixed the packetevents PR...

In any case I'll look into it when I have time (hopefully Wednesday)

**Comment by Axionize** [comment] 2024-11-15 01:04
UPDATE: it's definitely fixed. You probably forgot to do any one of the following from: checking out my branch, bumping the build version, running publishToMavenLocal, changing the packetevents grim version and then make the changes necessary's to avoid the CNE.

https://modrinth.com/plugin/lightning-grim-anticheat

~~Download grimac-2.3.69-custom-packetevents-2.6.1-fix-mappings (2.3.69-custom-a1) off of modrinth. Tell me if that jar still has issues.~~

Versions B9 and newer now include this fix.

Please re-open #3 if this issue persists.

**Comment by Axionize** [comment] 2024-11-15 01:08
Duplicate of #3

**Closed as completed by Axionize** 2024-11-15 01:08 UTC
